# VFX Reference Platform CY2025 pins (ASWF stack + related).
# Included from cmake/Versions.cmake when DAILYBOY_VFX_PLATFORM=2025.

set(DAILYBOY_VFX_PLATFORM_YEAR "2025")
set(DAILYBOY_CXX_STANDARD 17)
set(DAILYBOY_PYTHON_VERSION "3.11")
set(DAILYBOY_LINUX_GCC_VERSION "11.2")
set(DAILYBOY_OSX_DEPLOYMENT_TARGET "12.0")

set(DAILYBOY_OPENCOLORIO_VERSION "2.4")
set(DAILYBOY_OPENCOLORIO_GIT_TAG "v2.4.2")

set(DAILYBOY_OPENIMAGEIO_VERSION "3.0")
set(DAILYBOY_OPENIMAGEIO_GIT_TAG "v3.0.11.0")

set(DAILYBOY_ONETBB_VERSION "2021")
set(DAILYBOY_ONETBB_GIT_TAG "v2021.13.0")

set(DAILYBOY_IMATH_VERSION "3.1")
set(DAILYBOY_IMATH_BUILD_VERSION "3.1.12")
set(DAILYBOY_OPENEXR_VERSION "3.3")
set(DAILYBOY_OPENEXR_BUILD_VERSION "3.3.5")
