# VFX Reference Platform CY2026 pins (ASWF stack + related).
# Included from cmake/Versions.cmake when DAILYBOY_VFX_PLATFORM=2026.

set(DAILYBOY_VFX_PLATFORM_YEAR "2026")
set(DAILYBOY_CXX_STANDARD 20)
set(DAILYBOY_PYTHON_VERSION "3.13")
set(DAILYBOY_LINUX_GCC_VERSION "14.2")
set(DAILYBOY_OSX_DEPLOYMENT_TARGET "14.0")

set(DAILYBOY_OPENCOLORIO_VERSION "2.5")
set(DAILYBOY_OPENCOLORIO_GIT_TAG "v2.5.1")

set(DAILYBOY_OPENIMAGEIO_VERSION "3.0")
set(DAILYBOY_OPENIMAGEIO_GIT_TAG "v3.0.11.0")

set(DAILYBOY_ONETBB_VERSION "2022")
set(DAILYBOY_ONETBB_GIT_TAG "v2022.3.0")

set(DAILYBOY_IMATH_VERSION "3.2")
set(DAILYBOY_IMATH_BUILD_VERSION "3.2.2")
set(DAILYBOY_OPENEXR_VERSION "3.4")
set(DAILYBOY_OPENEXR_BUILD_VERSION "3.4.4")
