# VFX Reference Platform CY2024 pins (ASWF stack + related).
# Included from cmake/Versions.cmake when DAILYBOY_VFX_PLATFORM=2024.

set(DAILYBOY_VFX_PLATFORM_YEAR "2024")
set(DAILYBOY_CXX_STANDARD 17)
set(DAILYBOY_PYTHON_VERSION "3.11")
set(DAILYBOY_LINUX_GCC_VERSION "11.2")
set(DAILYBOY_OSX_DEPLOYMENT_TARGET "11.0")
# Visual Studio 2022 v17.4 → MSVC cl 19.34; Windows SDK 10.0.20348+.
set(DAILYBOY_WINDOWS_VS_VERSION "17.4")
set(DAILYBOY_WINDOWS_MSVC_VERSION "19.34")
set(DAILYBOY_WINDOWS_SDK_VERSION "10.0.20348.0")

set(DAILYBOY_OPENCOLORIO_VERSION "2.3")
set(DAILYBOY_OPENCOLORIO_GIT_TAG "v2.3.2")

set(DAILYBOY_OPENIMAGEIO_VERSION "3.0")
set(DAILYBOY_OPENIMAGEIO_GIT_TAG "v3.0.11.0")

# Intel TBB 2020 Update 3 (oneTBB migration deferred until CY2025).
# Unix: Makefile (gcc/clang). Windows: same Makefile with compiler=cl (MSVC).
set(DAILYBOY_ONETBB_VERSION "2020")
set(DAILYBOY_ONETBB_GIT_TAG "v2020.3")

set(DAILYBOY_IMATH_VERSION "3.1")
set(DAILYBOY_IMATH_BUILD_VERSION "3.1.12")
set(DAILYBOY_OPENEXR_VERSION "3.2")
set(DAILYBOY_OPENEXR_BUILD_VERSION "3.2.4")
