# VFX Reference Platform CY2026 toolchain on top of dailyboy-ci:base.
# Build: docker build -t dailyboy-ci:base -f docker/Dockerfile.base docker/
#        docker build -t dailyboy-ci:cy2026 -f docker/Dockerfile.cy2026 docker/

FROM dailyboy-ci:base

ENV Python3_EXECUTABLE=/usr/bin/python3.13

RUN apt-get update && apt-get install -y --no-install-recommends \
        software-properties-common \
    && add-apt-repository -y ppa:deadsnakes/ppa \
    && apt-get update && apt-get install -y --no-install-recommends \
        g++-14 \
        gcc-14 \
        python3.13 \
        python3.13-dev \
        python3.13-venv \
    && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 100 \
    && update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 100 \
    && update-alternatives --install /usr/bin/cc cc /usr/bin/gcc-14 100 \
    && update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++-14 100 \
    && update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-14 100 \
    && ln -sf /usr/bin/python3.13 /usr/local/bin/python3 \
    && ln -sf /usr/bin/python3.13 /usr/local/bin/python \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /src
